### PR TITLE
Config file

### PR DESCRIPTION
**Pull request by kelleydv**
Configure from a single file, rather than a bunch of environment variables.  This will allow for easy definition of the dev and prod environments.

### CODE REVIEW

**Comment by jakiestfu** [comment]
Id be more explicit with your configs in your git ignore, such as ignoring local.cnf and allowing everything else as opposed to only
Allowing default.cnf. You will eventually have more configs

**Comment by kelleydv** [comment]
You mean, I'll want to have more public configs?

**Comment by jakiestfu** [comment]
Oh sure. We have quite a few at Maker. Configs for our app (one for each environment), configs for deployment, configs for tests, etc.

You'll want to unit test your code at some point but maybe not yet.

**Comment by kelleydv** [comment]
OK.  Yes, tests sooner rather than later.  Still seems safer to explicitly add the configs that I want to be public though...

**Pull request merged**
