### PR TITLE
better abstraction of ushpa api

### PR DESCRIPTION
**Pull request by kelleydv**
Abstracting an APIs module

### CODE REVIEW

**Comment by kelleydv** [comment]
I felt that if I went with singular, it would imply that it was an api of the bapa app or something.

**Comment by jakiestfu** [comment]
I think my initial recommendation of "Apis" is incorrect, then. I'd opt for the term "services" instead, considering you're using ushpa as a service. That's what we reflectively call that logic in our code bases.

**Comment by kelleydv** [comment]
services sounds much better

**Comment by jakiestfu** [comment]
🙌💯👌

**Pull request merged**
